### ISSUE TITLE
No need to wait after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [naughtyStark/quad-copter-drone#1]
In the file "drone_simple.ino", after the Wire.requestFrom(), you have a 'while(Wire.available()<14);', but that while-loop is not needed. You may remove that line. There is nothing to wait for.

The Wire.requestFrom() waits until the I2C has completely finished and when it returns the received data is waiting in a buffer in the Wire library.

**Comment by sidtalia** [comment]
thanks! fixed that
